services:
  webapplication:
    image: webapplication
    build:
      context: .
      dockerfile: WebApplication/Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

